local E, L, V, P, G = unpack(ElvUI)

V.addOnSkins = {
	-- Addons
	AckisRecipeList = true,
	ACP = true,
	AdvancedTradeSkillWindow = true,
	Atlas = true,
	AtlasLoot = true,
	Auctionator = true,
	BindPad = true,
	BlackList = true,
	BugSack = true,
	BuyEmAll = true,
	CallToArms = true,
	Cartographer = true,
	Cartographer3 = true,
	Clique = true,
	DBM = true,
	Doom_CooldownPulse = true,
	EqCompare = true,
	FishingBuddy = true,
	FlightMap = true,
	MoveAnything = true,
	Omen = true,
	Outfitter = true,
	PAB = true,
	PallyPower = true,
	Postal = true,
	QuestGuru = true,
	QuestHelper = true,
	Recount = true,
	Skillet = true,
	Spy = true,
	Talented = true,
	TellMeWhen = true,
	TotemTimers = true,
	ZOMGBuffs = true,

	-- Blizzard
	Blizzard_WorldStateFrame = true,
}